### ISSUE TITLE
Non blocking receive and send

### ISSUE THREAD

**Issue by nnhw** [Midgrad/Dreka#33]
Migrate to asio's async func, but avoid using it's internals in Dreka

**Comment by MishkaRogachev** [comment]
Can close this issue?

**Comment by nnhw** [comment]
Yes, it’s done
________________________________
От: Mike R ***@***.***>
Отправлено: Thursday, December 30, 2021 3:49:19 PM
Кому: Midgrad/Dreka ***@***.***>
Копия: Elias Alberts ***@***.***>; Assign ***@***.***>
Тема: Re: [Midgrad/Dreka] Non blocking receive and send (#33)


Can close this issue?
