### ISSUE TITLE
Start a mission

### ISSUE THREAD

**Issue by mdhsieh** [Midgrad/Dreka#55]
Hi, how do I start a mission to automatically fly a drone after I have created some mission waypoints? I see the "Arm Throttle" Button but after press and hold it doesn't do anything in Mission mode. What steps am I missing?

The drone is simulated with ArduCopter SITL simulator, and I'm running Dreka on an Ubuntu 20.04 EC2 server from Amazon Web Services.

Thanks.

<img width="1440" alt="Screen Shot 2022-05-07 at 10 00 13 AM" src="https://user-images.githubusercontent.com/52055110/167265840-1633129e-a384-4124-915d-1244430e60de.png">

<img width="337" alt="Screen Shot 2022-05-07 at 10 50 43 AM" src="https://user-images.githubusercontent.com/52055110/167265957-6e87a7de-e3dd-4449-bafd-0bc7da9e3882.png">

**Comment by MishkaRogachev** [comment]
Hi! develop branch is under construction now, it will be fixed in a few weeks. 
Arming may be failing cause of [RTL_AUTOLAND](https://github.com/ArduPilot/ardupilot/pull/20345) flag is required in newest APM builds.

**Comment by mdhsieh** [comment]
Oh okay. Can you also help me understand, what are the steps normally needed to fly a drone from a mission with Dreka? Is it:
1. Add mission and create waypoints including takeoff and land
2. Set drone to Mission mode
3. Arm the drone 

And to fly manually:
1. Arm drone
2. Click a point and then click NavTo

**Comment by MishkaRogachev** [comment]
Using [APM](https://ardupilot.org/dev/docs/plane-sitlmavproxy-tutorial.html#taking-off)/PX4 in MISSION mode:
1. Add mission with takeoff item (after HOME item, it will be changed in a few weeks)
2. Upload mission to vehicle
3. Arm vehicle
4. Switch to mission mode

3-4 can be swaped, but in some cases vehicle can reject arming in mission mode

To takeoff manualy you need to setup [takeoff](https://ardupilot.org/plane/docs/takeoff-landingpage.html) conditions for your vehicle. For example

**Comment by mdhsieh** [comment]
Oh okay, thank you. I will wait for the changes then.
